### ISSUE TITLE
 /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Hongboo-Li** [triple-Mu/AI-on-Board#3]
我在执行这一步的时候python onnx2rknn.py报错：
E build: Catch exception when building RKNN model!
E build: Traceback (most recent call last):
E build: File "rknn/api/rknn_base.py", line 2012, in rknn.api.rknn_base.RKNNBase.build
E build: File "rknn/api/rknn_base.py", line 384, in rknn.api.rknn_base.RKNNBase._generate_rknn
E build: File "rknn/api/rknn_base.py", line 234, in rknn.api.rknn_base.RKNNBase._build_rknn
E build: ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/hbli/miniconda3/envs/rknn/lib/python3.8/site-packages/rknn/api/lib/linux-x86_64/cp38/librknnc.so)
W If you can't handle this error, please try updating to the latest version of the toolkit2 and runtime from:
https://eyun.baidu.com/s/3eTDMk6Y (Pwd: rknn) Path: RK_NPU_SDK / RK_NPU_SDK_1.X.0 / develop /
If the error still exists in the latest version, please collect the corresponding error logs and the model,
convert script, and input data that can reproduce the problem, and then submit an issue on:
https://redmine.rock-chips.com/ (Please consult our sales or FAE for the redmine account)
Build model failed!

**Comment by Hongboo-Li** [comment]
换成1.5.2还是不行，我没有权限更新GLIBC_2.29
